name: CI Build & Test

on:
  push:  
    branches: [ main ]
  pull_request:  
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libopencv-dev

      - name: Configure with CMake
        run: cmake -S . -B build

      - name: Build project
        run: cmake --build build -- -j$(nproc)

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
